### ISSUE TITLE
body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by yiyungent** [peter-evans/create-issue-from-file#1049]
I used `lycheeverse/lychee-action@v1.7.0` before this,    
I found that when `linkChecker summary` is too long, there will be an error, I don’t know how to solve it, thank you

```
Error: Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

![image](https://github.com/peter-evans/create-issue-from-file/assets/16939388/f21db064-4f74-4fa3-9aed-19cfbc9ec0b7)

**Comment by zkoppert** [comment]
The limit of 65536 characters is the limit set by GitHub for the issue description. That is to say that this limitation is not set by this action.

**Comment by yiyungent** [comment]
Thanks！！！
