### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by khemarato** [peter-evans/create-issue-from-file#1716]
I used to get email notifications for Issues created through this action, but I don't any more. Any idea what changed? Is there some new setting I need to toggle on the GitHub side, or...?

Thanks!

**Comment by peter-evans** [comment]
Hi @khemarato 

Notifications on GitHub are independent of this action. So I would imagine it's either a notifications setting, or you've stopped watching the repository where the issues are being created.

If you have trouble resolving it I would suggest reaching out to GitHub support.
