### ISSUE TITLE
Template issue body

### ISSUE THREAD

**Issue by jeluard** [peter-evans/create-issue-from-file#206]
Hey! Thanks for creating this action!

Is there a way to fill values from the github workflow in the issue template? Those would be replaced at issue creation time.

**Comment by peter-evans** [comment]
Hi @jeluard 

Unfortunately there isn't a way to do that with this action alone. This action expects that the target file is pre-processed with any dynamic information necessary. 

It should be possible to fill-in template values in a step before this action runs. I did a quick search on the Actions marketplace and found this action that might help. There may be other similar actions if this one isn't suitable.
https://github.com/marketplace/actions/template-env

**Comment by jeluard** [comment]
Thanks for the research ! :)
